# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  any-date-parser = nodeEnv.buildNodePackage {
    name = "any-date-parser";
    packageName = "any-date-parser";
    version = "1.5.4";
    src = fetchurl {
      url = "https://registry.npmjs.org/any-date-parser/-/any-date-parser-1.5.4.tgz";
      sha512 = "S4gl9UmXNk9XXSQxp5w5harUD6aM0fepyL3dZM/B3znX57sWf792hS2UvvCFIHECfpsqfKbQ+cqWBky4AKyRIg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Parse a wide range of date formats including human-input dates";
      homepage = "https://github.com/kensnyder/any-date-parser#readme";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
